// @ts-nocheck
import { MessageMethod } from './message';
import { NotificationMethod } from './notification';
import { ModalMethod } from './modal';
import { DrawerMethod } from './drawer';

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: (typeof import('arco-next'))['Affix'];
    AAlert: (typeof import('arco-next'))['Alert'];
    AAnchor: (typeof import('arco-next'))['Anchor'];
    AAnchorLink: (typeof import('arco-next'))['AnchorLink'];
    AAutoComplete: (typeof import('arco-next'))['AutoComplete'];
    AAvatar: (typeof import('arco-next'))['Avatar'];
    AAvatarGroup: (typeof import('arco-next'))['AvatarGroup'];
    ABackTop: (typeof import('arco-next'))['BackTop'];
    ABadge: (typeof import('arco-next'))['Badge'];
    ABreadcrumb: (typeof import('arco-next'))['Breadcrumb'];
    ABreadcrumbItem: (typeof import('arco-next'))['BreadcrumbItem'];
    AButton: (typeof import('arco-next'))['Button'];
    AButtonGroup: (typeof import('arco-next'))['ButtonGroup'];
    ACalendar: (typeof import('arco-next'))['Calendar'];
    ACard: (typeof import('arco-next'))['Card'];
    ACardMeta: (typeof import('arco-next'))['CardMeta'];
    ACardGrid: (typeof import('arco-next'))['CardGrid'];
    ACarousel: (typeof import('arco-next'))['Carousel'];
    ACarouselItem: (typeof import('arco-next'))['CarouselItem'];
    ACascader: (typeof import('arco-next'))['Cascader'];
    ACascaderPanel: (typeof import('arco-next'))['CascaderPanel'];
    ACheckbox: (typeof import('arco-next'))['Checkbox'];
    ACheckboxGroup: (typeof import('arco-next'))['CheckboxGroup'];
    ACollapse: (typeof import('arco-next'))['Collapse'];
    ACollapseItem: (typeof import('arco-next'))['CollapseItem'];
    AColorPicker: (typeof import('arco-next'))['ColorPicker'];
    AComment: (typeof import('arco-next'))['Comment'];
    AConfigProvider: (typeof import('arco-next'))['ConfigProvider'];
    ADatePicker: (typeof import('arco-next'))['DatePicker'];
    AWeekPicker: (typeof import('arco-next'))['WeekPicker'];
    AMonthPicker: (typeof import('arco-next'))['MonthPicker'];
    AYearPicker: (typeof import('arco-next'))['YearPicker'];
    AQuarterPicker: (typeof import('arco-next'))['QuarterPicker'];
    ARangePicker: (typeof import('arco-next'))['RangePicker'];
    ADescriptions: (typeof import('arco-next'))['Descriptions'];
    ADescriptionsItem: (typeof import('arco-next'))['DescriptionsItem'];
    ADivider: (typeof import('arco-next'))['Divider'];
    ADrawer: (typeof import('arco-next'))['Drawer'];
    ADropdown: (typeof import('arco-next'))['Dropdown'];
    ADoption: (typeof import('arco-next'))['Doption'];
    ADgroup: (typeof import('arco-next'))['Dgroup'];
    ADsubmenu: (typeof import('arco-next'))['Dsubmenu'];
    AEmpty: (typeof import('arco-next'))['Empty'];
    AForm: (typeof import('arco-next'))['Form'];
    AFormItem: (typeof import('arco-next'))['FormItem'];
    AGrid: (typeof import('arco-next'))['Grid'];
    AGridItem: (typeof import('arco-next'))['GridItem'];
    ACol: (typeof import('arco-next'))['Col'];
    ARow: (typeof import('arco-next'))['Row'];
    AImage: (typeof import('arco-next'))['Image'];
    AImagePreview: (typeof import('arco-next'))['ImagePreview'];
    AImagePreviewAction: (typeof import('arco-next'))['ImagePreviewAction'];
    AImagePreviewGroup: (typeof import('arco-next'))['ImagePreviewGroup'];
    AInput: (typeof import('arco-next'))['Input'];
    AInputGroup: (typeof import('arco-next'))['InputGroup'];
    AInputSearch: (typeof import('arco-next'))['InputSearch'];
    AInputPassword: (typeof import('arco-next'))['InputPassword'];
    AInputNumber: (typeof import('arco-next'))['InputNumber'];
    AInputTag: (typeof import('arco-next'))['InputTag'];
    ALayout: (typeof import('arco-next'))['Layout'];
    ALayoutHeader: (typeof import('arco-next'))['LayoutHeader'];
    ALayoutContent: (typeof import('arco-next'))['LayoutContent'];
    ALayoutFooter: (typeof import('arco-next'))['LayoutFooter'];
    ALayoutSider: (typeof import('arco-next'))['LayoutSider'];
    ALink: (typeof import('arco-next'))['Link'];
    AList: (typeof import('arco-next'))['List'];
    AListItem: (typeof import('arco-next'))['ListItem'];
    AListItemMeta: (typeof import('arco-next'))['ListItemMeta'];
    AMention: (typeof import('arco-next'))['Mention'];
    AMenu: (typeof import('arco-next'))['Menu'];
    AMenuItem: (typeof import('arco-next'))['MenuItem'];
    AMenuItemGroup: (typeof import('arco-next'))['MenuItemGroup'];
    ASubMenu: (typeof import('arco-next'))['SubMenu'];
    AModal: (typeof import('arco-next'))['Modal'];
    APageHeader: (typeof import('arco-next'))['PageHeader'];
    APagination: (typeof import('arco-next'))['Pagination'];
    APopconfirm: (typeof import('arco-next'))['Popconfirm'];
    APopover: (typeof import('arco-next'))['Popover'];
    AProgress: (typeof import('arco-next'))['Progress'];
    ARadio: (typeof import('arco-next'))['Radio'];
    ARadioGroup: (typeof import('arco-next'))['RadioGroup'];
    ARate: (typeof import('arco-next'))['Rate'];
    AResizeBox: (typeof import('arco-next'))['ResizeBox'];
    AResult: (typeof import('arco-next'))['Result'];
    ASelect: (typeof import('arco-next'))['Select'];
    AOption: (typeof import('arco-next'))['Option'];
    AOptgroup: (typeof import('arco-next'))['Optgroup'];
    ASkeleton: (typeof import('arco-next'))['Skeleton'];
    ASkeletonLine: (typeof import('arco-next'))['SkeletonLine'];
    ASkeletonShape: (typeof import('arco-next'))['SkeletonShape'];
    ASlider: (typeof import('arco-next'))['Slider'];
    ASpace: (typeof import('arco-next'))['Space'];
    ASpin: (typeof import('arco-next'))['Spin'];
    ASplit: (typeof import('arco-next'))['Split'];
    AStatistic: (typeof import('arco-next'))['Statistic'];
    ACountdown: (typeof import('arco-next'))['Countdown'];
    ASteps: (typeof import('arco-next'))['Steps'];
    AStep: (typeof import('arco-next'))['Step'];
    ASwitch: (typeof import('arco-next'))['Switch'];
    ATable: (typeof import('arco-next'))['Table'];
    AThead: (typeof import('arco-next'))['Thead'];
    ATd: (typeof import('arco-next'))['Td'];
    ATh: (typeof import('arco-next'))['Th'];
    ATr: (typeof import('arco-next'))['Tr'];
    ATbody: (typeof import('arco-next'))['Tbody'];
    ATableColumn: (typeof import('arco-next'))['TableColumn'];
    ATabs: (typeof import('arco-next'))['Tabs'];
    ATabPane: (typeof import('arco-next'))['TabPane'];
    ATag: (typeof import('arco-next'))['Tag'];
    ATextarea: (typeof import('arco-next'))['Textarea'];
    ATimePicker: (typeof import('arco-next'))['TimePicker'];
    ATimeline: (typeof import('arco-next'))['Timeline'];
    ATimelineItem: (typeof import('arco-next'))['TimelineItem'];
    ATooltip: (typeof import('arco-next'))['Tooltip'];
    ATransfer: (typeof import('arco-next'))['Transfer'];
    ATree: (typeof import('arco-next'))['Tree'];
    ATreeSelect: (typeof import('arco-next'))['TreeSelect'];
    ATrigger: (typeof import('arco-next'))['Trigger'];
    ATypography: (typeof import('arco-next'))['Typography'];
    ATypographyParagraph: (typeof import('arco-next'))['TypographyParagraph'];
    ATypographyTitle: (typeof import('arco-next'))['TypographyTitle'];
    ATypographyText: (typeof import('arco-next'))['TypographyText'];
    AUpload: (typeof import('arco-next'))['Upload'];
    AVerificationCode: (typeof import('arco-next'))['VerificationCode'];
    AWatermark: (typeof import('arco-next'))['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
